// Fragevorlage:
// {
//     category: "Toleranzen",
//     level: "N",
//     frage: "Frage",
//     fragebild: [],
//     fragebild_2: [],
//     antwort: "Antwort",
//     erklaerung: "Erklärung",
//     hinweis: "",
//     beispiel: "",
//     beispiel_bild: [],
//     beispiel_2: "",
//     beispiel_bild_2: []
// }

const questions_data = [

    // ==========================================
    // KATEGORIE: Drehen
    // ==========================================
    {
        category: "Drehen",
        level: "N",
        frage: "Was ist Drehen für ein Fertigungsverfahren?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Drehen ist ein spanendes Fertigungsverfahren.",
        erklaerung: "Das Werkstück führt dabei die **Hauptschnittbewegung** durch, indem es sich um seine eigene Achse dreht.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Drehen",
        level: "N",
        frage: "Welche Hauptkomponenten gehören zu einer Drehmaschine?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Maschinenbett,\n- Hauptspindel,\n- Spannfutter,\n- Werkzeughalter,\n- Support,\n- Reitstock.",
        erklaerung: "Die **Hauptspindel** nimmt das Spannfutter auf, der **Support** führt das Werkzeug und der **Reitstock** stützt lange Werkstücke ab oder nimmt Bohrwerkzeuge auf.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Drehen",
        level: "N",
        frage: "Welche drei wichtigen Arbeitsbewegungen werden beim Drehen unterschieden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Hauptschnittbewegung (Drehbewegung des Werkstücks),\n\n- Vorschubbewegung (längs oder quer zur Drehachse),\n\n- Zustellbewegung (Einstellung der Schnitttiefe).",
        erklaerung: "Durch das Zusammenspiel dieser drei Bewegungen wird der Span kontinuierlich vom Werkstück abgenommen.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Drehen",
        level: "N",
        frage: "Nenne mindestens vier wichtige Drehverfahren aus dem Skript.",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Längsdrehen,\n- Plandrehen,\n- Einstechen,\n- Abstechen,\n- Gewindedrehen,\n- Kegeldrehen,\n- Formdrehen\n- Innendrehen.",
        erklaerung: "",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Drehen",
        level: "N",
        frage: "Mit welchen Spannmitteln kann ein Werkstück auf der Drehmaschine gespannt werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Dreibackenfutter,\n- Vierbackenfutter,\n- Spannzange,\n- zwischen Spitzen\n- Planscheibe.",
        erklaerung: "Bei langen Werkstücken wird zusätzlich eine **Reitstockspitze** oder eine **Lünette** zur Abstützung eingesetzt.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Drehen",
        level: "N",
        frage: "Mit welchen Vorrichtungen können lange Werkstücke auf der Drehmaschine abgestützt werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Reitstock,\n- Lünette.",
        erklaerung: "Eine Abstützung ist oft notwendig, um Vibrationen zu vermeiden und die Maßhaltigkeit zu gewährleisten.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },


    {
        category: "Drehen",
        level: "N",
        frage: "Wie groß ist der typische Spitzenradius von Hartmetall-Wendeschneidplatten zum Schlichten?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Sie haben häufig einen kleinen Spitzenradius von rε = 0,4 mm.",
        erklaerung: "Dies muss bei kleinen Innenkantenbrüchen und Innenradien auf technischen Zeichnungen beachtet werden.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Drehen",
        level: "N",
        frage: "Was muss ein Technischer Zeichner bei der Konstruktion von Drehteilen hinsichtlich Radien und Fasen an Kanten beachten?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Speziell für konventionelles Drehen gilt:\nan Außenkanten Fasen, an Wellenübergängen (Innen-Radien) ein (kleiner) Radius.",
        erklaerung: "Radien an Außenkanten erfordern einen extra Drehmeißel, während Innenradien gut zum kleinen Spitzenradius des Werkzeugs passen.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Drehen",
        level: "N",
        frage: "Warum sind an Drehteilen oftmals **Zentrierbohrungen** vorzusehen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Um lange Werkstück mittels Spitze abzustützen zu können\n\nEventuell benötigt ein folgender Bearbeitungsschritt (zB. Schleifen) eine Zentrierbohrung zum Spannen.",
        erklaerung: "",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },


    // ==========================================
    // KATEGORIE: Fräsen
    // ==========================================
    {
        category: "Fräsen",
        level: "N",
        frage: "Was ist Fräsen für ein Fertigungsverfahren und wer führt die Hauptschnittbewegung aus?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Fräsen ist ein spanendes Fertigungsverfahren mit geometrisach bestimmten Schneiden. Die Hauptschnittbewegung wird vom Fräser ausgeführt.",
        erklaerung: "\nDas Werkstück oder der Fräser führt dabei die Vorschubbewegung aus.\nHergestellt werden können ebene Flächen, Nuten, Taschen, Absätze und Konturen.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Fräsen",
        level: "N",
        frage: "Welche wichtigen Fräsverfahren werden im Skript genannt?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Planfräsen,\n- Umfangsfräsen,\n- Nutfräsen,\n- Taschenfräsen,\n- Profilfräsen und\n- Gewindefräsen.",
        erklaerung: "Jedes Verfahren ist auf bestimmte geometrische Formen und Oberflächenstrukturen optimiert.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Fräsen",
        level: "N",
        frage: "Worin liegt der Unterschied zwischen Umfangsfräsen und Stirnfräsen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Beim Umfangsfräsen tragen die Schneiden am Umfang des Fräsers das Material ab.\n\nBeim Stirnfräsen bearbeiten die Schneiden an der Stirnseite die Werkstückoberfläche.",
        erklaerung: "Die Art des Fräsens beeinflusst die Richtung und Struktur der Bearbeitungsspuren, was z. B. bei Dichtflächen für O-Ringe wichtig ist.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Fräsen",
        level: "N",
        frage: "Was versteht man unter **Schruppen**?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Schruppen ist die grobe Vorbearbeitung mit hohem Materialabtrag und rauer Oberfläche.",
        erklaerung: "Für das Schlichten muss etwas Aufmaß stehen bleiben.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Fräsen",
        level: "N",
        frage: "Was versteht man unter **Schlichten**",
        fragebild: [],
        fragebild_2: [],
        antwort: "Schlichten ist die Fertigbearbeitung mit geringer Zustellung.\nSchlichten ergibt hohe Oberflächengüten sowie Maß- und Formgenauigkeiten.",
        erklaerung: "Beim Schlichten arbeitet man mit höherer Schnittgeschwindigkeit, aber geringem Vorschub und kleiner Zustellung.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },


    {
        category: "Fräsen",
        level: "N",
        frage: "Welche Fräswerkzeuge werden für welche Anwendungen eingesetzt (Nenne vier Beispiele)?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Schaftfräser (Nuten, Taschen, Absätze),\n- Planfräser (größere ebene Flächen),\n- Radiusfräser (Radien/gekrümmte Übergänge)\n- Modulfräser (Zahnradfertigung).",
        erklaerung: "\nEbenfalls gängig sind Nutenfräser für Schlitze und Formfräser für spezielle Profile.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Fräsen",
        level: "N",
        frage: "Warum ist eine völlig scharfe Innenecke bei einer gefrästen Innenkontur nicht möglich?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Weil der Fräser rund ist und daher konstruktionsbedingt immer ein Innenradius entsteht, der vom Fräserdurchmesser abhängt.",
        erklaerung: "Ein Technischer Zeichner muss deshalb darauf achten, keine zu kleinen Eckenradien vorzugeben.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Fräsen",
        level: "V",
        frage: "Welche Zusatzeinrichtungen können an Fräsmaschinen eingesetzt werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Teilapparat,\n- Rundtisch,\n- Spiralnutfräseinrichtung und\n- Schleifkopf.",
        erklaerung: "Ein Teilapparat dient beispielsweise der Zahnradherstellung oder dem Bohren von Flanschteilkreisen.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    // ==========================================
    // KATEGORIE: Schleifen
    // ==========================================
    {
        category: "Schleifen",
        level: "N",
        frage: "Wie ist Schleifen definiert?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Schleifen ist ein spanabhebendes Bearbeitungsverfahren mit **geometrisch unbestimmten** Schneiden.",
        erklaerung: "\nDie Lage der einzelnen Schleifkörner und Schneiden im Schleifkörper ist unbestimmt.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Schleifen",
        level: "N",
        frage: "Nenne vier wesentliche Zwecke des Schleifens.",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Erreichen einer hohen Oberflächengüte,\n- Bearbeitung harter Werkstoffe,\n- Erzielung hoher Maß- und Formgenauigkeit sowie\n- Trennen von Werkstücken,\n- Schärfen von Werkzeugen.",
        erklaerung: "Erreichbare Rauheiten liegen oft im Bereich von Ra 0,012 bis Ra 6,3.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Schleifen",
        level: "N",
        frage: "Aus welchen drei Hauptbestandteilen ist ein Schleifkörper aufgebaut?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Schleifkörner,\n- Bindemittel und\n- Poren.",
        erklaerung: "Schleifkörner zerspanen den Werkstoff.\n\nDas Bindemittel hält die Körner zusammen.\n\nDie Poren schaffen Platz für Späne sowie die Kühlstoffzufuhr.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },







    {
        category: "Schleifen",
        level: "V",
        frage: "Welche vier Schleifkornarten werden im Skript genannt und wofür werden sie eingesetzt?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Korund (ungehärtete/weniger harte Stähle bis HSS),\n- Siliziumkarbid (Hartmetall, Keramik, Glas, NE-Metalle),\n- Bornitrid (HSS, gehärtete Stähle)\n- Diamant (Hartmetall, Keramik, Glas).",
        erklaerung: "\nWichtig: Diamant darf wegen zu hoher Schleiftemperaturen nicht für Stahl verwendet werden, da der Kohlenstoff in den Stahl diffundieren würde.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Schleifen",
        level: "V",
        frage: "Warum darf Diamant nicht für das Schleifen von Stahl verwendet werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Bei den hohen Schleiftemperaturen diffundiert Kohlenstoff aus dem Diamant in den Stahl, wodurch der Diamant zerstört wird.",
        erklaerung: "Der Kohlenstoff diffundiert in den Stahl heißt, er wandert vom Diamant (100%-C) in den Stahl.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Schleifen",
        level: "V",
        frage: "Auf einem Schleifbock ist eine **weiße** und **grüne** Schleifscheibe montiert.\nWelche Schleifkornart wird das jeweils sein?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die weiße Schleifscheibe ist aus Korund, die grüne Schleifscheibe aus Siliziumkarbid.",
        erklaerung: "",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },



    {
        category: "Schleifen",
        level: "N",
        frage: "Was versteht man unter der **Härte** einer Schleifscheibe?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Härte einer Schleifscheibe beschreibt den Widerstand der Bindung gegen das Ausbrechen der Schleifkörner.",
        erklaerung: "",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Schleifen",
        level: "N",
        frage: "Was beschreibt die **Körnung** einer Schleifscheibe?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Körnung einer Schleifscheibe beschreibt die Größe der Schleifkörner.",
        erklaerung: "z.B. 12 bedeutet eine Maschenzahl von 12 auf 1 Inch Länge",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Schleifen",
        level: "N",
        frage: "Welche Aufgabe hat das **Bindemittel** einer Schleifscheibe?",
        fragebild: [],
        fragebild_2: [],
        antwort: "hält die einzelnen Schleifkörner zusammen, bis sie stumpf geworden sind.\nDanach sollte es das Korn loslassen.",
        erklaerung: "",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Schleifen",
        level: "N",
        frage: "Was beschreibt das **Gefüge** einer Schleifscheibe?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das Verhältnis von Schleifkörnern, Bindung und Porenraum.",
        erklaerung: "Das Gefüge wird durch die Porosität der Schleifscheibe bestimmt.\nEine hohe Porosität bedeutet, dass die Scheibe viele Poren hat, was die Kühlung und Spanabfuhr verbessert.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },


    {
        category: "Schleifen",
        level: "N",
        frage: "Was versteht man unter **weicher** Schleifscheibe?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Weiche Schleifscheiben haben eine weiche Bindung. Wenn die Körner abstumpfen, gibt die weiche Bindung sie frei, damit neue scharfe Körner zum Einsatz kommen (Selbstschärfung).",
        erklaerung: "",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Schleifen",
        level: "N",
        frage: "Was versteht man unter **harter** Schleifscheibe?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Harte Schleifscheiben haben eine harte Bindung. Sie halten die Körner fester zusammen und geben sie nicht so leicht frei.",
        erklaerung: "Das Korn wird dadurch länger genutzt.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Schleifen",
        level: "N",
        frage: "Wie verhält sich die Härte von Schleifscheiben zu den zu bearbeitenden Werkstoffen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Weiche Werkstoffe werden mit harten Schleifscheiben bearbeitet, harte Werkstoffe mit weichen Schleifscheiben.",
        erklaerung: "",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Schleifen",
        level: "N",
        frage: "Warum werden **weiche Werkstoffe** mit **harten Schleifscheiben** bearbeitet?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Weiche Werkstoffe stumpfen Körner kaum ab und sollen daher nicht vorzeitig ausbrechen.\nDicke Späne benötigen zudem eine große Kornhaltekraft – also harte Scheiben.",
        erklaerung: "",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Schleifen",
        level: "N",
        frage: "Warum werden **harte Werkstoffe** mit **weichen Schleifscheiben** bearbeitet?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Harte Werkstoffe lassen Körner schnell abstumpfen. Die Bindung soll stumpfe Körner freigeben damit neue zum Einsatz kommen können (Selbstschärfung).",
        erklaerung: "",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },


    {
        category: "Schleifen",
        level: "N",
        frage: "Aus welchen Gründen müssen Schleifkörper 'abgerichtet' werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Um eine abgenützte Scheibe in Form zu bringen,\n- sie zu schärfen,\n- verschmierte Poren zu öffnen,\n- die Oberflächengüte zu steigern\n- Rund- oder Planlauf herzustellen.",
        erklaerung: "Als Abrichtwerkzeuge werden meist Diamantstifte, -fliesen oder -rollen verwendet.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Schleifen",
        level: "N",
        frage: "Warum müssen Schleifscheiben unbedingt ausgewuchtet werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Weil Unwucht Fliehkräfte und Schwingungen erzeugt, die die Lebensdauer der Lager, der Schleifscheibe und der Maschine reduzieren sowie die Oberflächenqualität verschlechtern.",
        erklaerung: "",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Schleifen",
        level: "N",
        frage: "Was muss bei der Konstruktion von Werkstücken mit geschliffenen Flächen (z. B. Wellen) beachtet werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Sie müssen geeignete Spannmöglichkeiten wie Zentrierbohrungen und Freistiche zum Schleifen aufweisen.",
        erklaerung: "Typische Spannmöglichkeiten sind das:\n- Spannen zwischen Spitzen,\n- auf Hydrospanndornen,\n- in Backenfutter oder\n- mittels Magnetplatten.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Schleifen",
        level: "N",
        frage: "Skizziere einen:\n- Schleiftopf,\n- Schleifteller,\n- Schleifstift.",
        fragebild: [],
        fragebild_2: [],
        antwort: "",
        erklaerung: "",
        hinweis: "geht der Hinweis?",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },


    // ---------------------------------------------------------
    // 1. Planschleifen (Flächenschleifen)
    // ---------------------------------------------------------

    {
        category: "Schleifverfahren",
        level: "N",
        frage: "Was versteht man unter Umfangsschleifen beim Planschleifen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Beim Umfangsschleifen wird mit dem Umfang der Schleifscheibe geschliffen.",
        erklaerung: "Durch die geringe Kontaktlänge entsteht dabei nur wenig Schleifwärme.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "N",
        frage: "Was zeichnet das Stirnschleifen beim Planschleifen aus?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Beim Stirnschleifen erfolgt das Schleifen mit der Stirnseite der Schleifscheibe.",
        erklaerung: "Wegen der großen Kontaktfläche entsteht dabei sehr viel Schleifwärme.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "VN",
        frage: "Welche Prozessparameter kennzeichnen das Pendelschleifen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das Pendelschleifen zeichnet sich durch eine kleine Zustellung (ca. 0,02–0,1 mm) und einen hohen Vorschub aus.",
        erklaerung: "Die geringe Kontaktlänge führt zu geringer Wärmeentwicklung am Werkstück.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "V",
        frage: "Welche Merkmale und Prozessbedingungen kennzeichnen das Tiefschleifen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das Tiefschleifen zeichnet sich durch eine große Zustellung (z. B. 8 mm) und einen langsamen Vorschub aus. Es bietet eine hohe Schleifleistung und gute Profilstandzeit, erfordert aber hochporöse Schleifscheiben und gute Kühlung.",
        erklaerung: "Durch den tiefen Eingriff entsteht viel Schleifwärme, weshalb die Kühlung eine zentrale Rolle spielt.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "VN",
        frage: "Warum entsteht beim Stirnschleifen mehr Schleifwärme als beim Umfangsschleifen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Beim Stirnschleifen liegt eine wesentlich größere Kontaktfläche zwischen Werkstück und Schleifscheibe vor als beim Umfangsschleifen.",
        erklaerung: "Eine größere Kontaktfläche erschwert den Wärmeabtransport sowie das Eindringen von Kühlschmierstoff.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },

    // ---------------------------------------------------------
    // 2. Rundschleifen
    // ---------------------------------------------------------
    {
        category: "Schleifverfahren",
        level: "N",
        frage: "Welche Oberflächen werden beim Außenrundschleifen bearbeitet?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Beim Außenrundschleifen werden Außendurchmesser von zylindrischen Werkstücken bearbeitet.",
        erklaerung: "Aufgrund der kleinen Kontaktfläche entstehen wenig Schleifwärme und gute Kühlmöglichkeiten.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "VN",
        frage: "Welche Probleme und Besonderheiten treten beim Innenrundschleifen auf?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Beim Innenrundschleifen entstehen eine große Kontaktfläche und hohe Schleifwärme. Zudem bestehen schlechte Kühlmöglichkeiten, schlechte Sicht und die lange, dünne Schleifspindel kann instabil sein.",
        erklaerung: "Der Schleifkörper sollte ca. 60–80 % des Bohrungsdurchmessers betragen.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "VN",
        frage: "Wie groß sollte der Schleifkörper beim Innenrundschleifen im Verhältnis zur Bohrung gewählt werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Der Schleifkörper sollte ca. 60–80 % des Bohrungsdurchmessers betragen.",
        erklaerung: "Dies gewährleistet ein optimales Verhältnis zwischen Eigensteifigkeit des Werkzeugs und genügend Spanraum bzw. Kühlmittelzufuhr.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "N",
        frage: "Was ist der Unterschied zwischen Längsschleifen und Einstechschleifen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Beim Längsschleifen bewegt sich die Schleifscheibe axial am Werkstück entlang. Beim Einstechschleifen wird die Schleifscheibe radial zugestellt.",
        erklaerung: "Längsschleifen eignet sich für längere Flächen, während Einstechschleifen für kurze Flächen, Absätze oder Konturen genutzt wird.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "VN",
        frage: "Welchen besonderen Vorteil bietet das Schrägeinstechschleifen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Beim Schrägeinstechschleifen können gleichzeitig zylindrische Flächen und Stirnflächen bearbeitet werden.",
        erklaerung: "Dadurch lassen sich zum Beispiel Wellenansätze in einer einzigen Aufspannung fertigschleifen.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },

    // ---------------------------------------------------------
    // 3. Spitzenloses Schleifen (Centerless Schleifen)
    // ---------------------------------------------------------
    {
        category: "Schleifverfahren",
        level: "N",
        frage: "Aus welchen drei Grundelementen besteht der Aufbau beim spitzenlosen Schleifen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Grundelemente sind die Schleifscheibe, die Regelscheibe und das Schleiflineal.",
        erklaerung: "Das Werkstück liegt auf dem Schleiflineal auf und wird zwischen Schleif- und Regelscheibe geführt.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "VN",
        frage: "Welche Aufgaben haben Regelscheibe und Schleiflineal beim spitzenlosen Schleifen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die langsam drehende Regelscheibe regelt die Drehzahl des Werkstücks. Das Schleiflineal hält das Werkstück auf der richtigen Höhe.",
        erklaerung: "Die schnell drehende Schleifscheibe führt die eigentliche Spanabhebung aus.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "VN",
        frage: "Für welche Werkstücke eignet sich das Durchgangsschleifen beim spitzenlosen Schleifen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das Durchgangsschleifen eignet sich für durchgehend zylindrische Teile ohne Bund.",
        erklaerung: "Die Regelscheibe sorgt durch leichtes Anstellen für den axialen Vorschub des Werkstücks.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "VN",
        frage: "Wann kommt das Einstechschleifen beim spitzenlosen Schleifen zum Einsatz?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Es wird für Werkstücke mit Bund oder spezieller Kontur verwendet, bei denen das Werkstück axial nicht bewegt wird.",
        erklaerung: "Die Zustellung der Scheiben erfolgt rein radial.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },

    // ---------------------------------------------------------
    // 4. Trowalisieren (Gleitschleifen)
    // ---------------------------------------------------------
    {
        category: "Schleifverfahren",
        level: "N",
        frage: "Wie läuft der Bearbeitungsprozess beim Trowalisieren (Gleitschleifen) ab?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Werkstücke werden zusammen mit Schleifkörpern in einem Arbeitsbehälter in Bewegung versetzt.",
        erklaerung: "Durch das ständige Aneinanderreiben entgratet und glättet sich die Oberfläche der Werkstücke.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },
    {
        category: "Schleifverfahren",
        level: "VN",
        frage: "Welche Fertigungsaufgaben können mit dem Gleitschleifen durchgeführt werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Grate entfernen, Oberflächen glätten, Kanten verrunden (Kantenbruch) sowie Werkstücke polieren.",
        erklaerung: "Das Verfahren eignet sich besonders für die wirtschaftliche Serienbearbeitung vieler kleiner Werkstücke gleichzeitig.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    },

    // ---------------------------------------------------------
    // 5. Trennschleifen
    // ---------------------------------------------------------
    {
        category: "Schleifverfahren",
        level: "N",
        frage: "Wie werden Werkstücke beim Trennschleifen bearbeitet?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Beim Trennschleifen werden Werkstücke mit einer dünnen Trennscheibe getrennt.",
        erklaerung: "Aufgrund der geringen Scheibenbreite entsteht ein schmaler Schnitt mit geringem Materialverlust.",
        hinweis: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: []
    }

]


window.questionsData = questions_data;
